#!/bin/bash
clear
########## COLOR ##########
ORANGE='\033[0;33m'
pp="\033[42m"
xz="\033[1;93m"
z="\033[96m"
NC="\033[0m"
g="\033[1;92m"
y='\033[1;33m' #yellow
clear
IPVPES="https://raw.githubusercontent.com/hokagelegend9999/ijin/refs/heads/main/alpha"
clear
ipsaya=$(curl -sS ipv4.icanhazip.com)
data_server=$(curl -v --insecure --silent https://google.com/ 2>&1 | grep Date | sed -e 's/< Date: //')
date_list=$(date +"%Y-%m-%d" -d "$data_server")
checking_sc() {
  useexp=$(wget -qO- $IPVPES | grep $ipsaya | awk '{print $3}')
  if [[ $date_list < $useexp ]]; then
    echo -ne
  else
    echo -e "\033[1;93m────────────────────────────────────────────\033[0m"
    echo -e "\033[42m          404 NOT FOUND AUTOSCRIPT          \033[0m"
    echo -e "\033[1;93m────────────────────────────────────────────\033[0m"
    echo -e ""
    echo -e "            ${RED}PERMISSION DENIED !${NC}"
    echo -e "   \033[0;33mYour VPS${NC} $ipsaya \033[0;33mHas been Banned${NC}"
    echo -e "     \033[0;33mBuy access permissions for scripts${NC}"
    echo -e "             \033[0;33mContact Admin :${NC}"
    echo -e "      \033[0;36mTelegram${NC} https://t.me/hokagelegend1"
    echo -e "\033[1;93m────────────────────────────────────────────\033[0m"
    exit
  fi
}
checking_sc
clear
echo -e "  ${y}┌──────────────────────────────────────────┐${NC}"
echo -e "  ${y}│${NC}                 MENU BOT            $NC"
echo -e "  ${y}└──────────────────────────────────────────┘${NC}"
echo -e "  ${y}┌──────────────────────────────────────────┐${NC}"
echo -e "  ${y}│${NC}${g} 1.${NC} \033[0;36m Menu BOT Panel ${NC}"
echo -e "  ${y}│${NC}${g} 2.${NC} \033[0;36m Menu BOT Notifikasi ${NC}"
echo -e "  ${y}│${NC}${g} 3.${NC} \033[0;36m Menu BOT Backup ${NC}"
echo -e "  ${y}│${NC}${g} x.${NC} \033[0;36m Exit Menu BOT ${NC}"
echo -e "  ${y}└──────────────────────────────────────────┘${NC}"
echo -e ""
read -p "   Select From Options [ 1 - 3 or x ] : " menu
case $menu in
1) clear ; checking_sc ; mbot-panel ;;
2) clear ; checking_sc ; bot ;;
3) clear ; checking_sc ; 
echo -e "Note: "
echo -e "Sebelum Menggunakan BOT Backup"
echo -e "Harap Setup Dulu ID & Bot Token Kamu !"
sleep 2
mbot-backup ;;
0) menu ;;
*) m-bot ;;
esac
